# Projeto Final – Estudo da População

## 1. Importação dos dados

In [1]:
import pandas as pd

caminho_planilha = "CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"
base_censo = pd.read_excel(caminho_planilha, sheet_name="Municípios", header=2)
base_censo = base_censo.dropna(subset=["UF", "NOME DO MUNICÍPIO"]).copy()

print(f"Registros carregados: {len(base_censo):,}")
base_censo.head()

Registros carregados: 5,570

   Unnamed: 0  ... População Censo 2022
0         NaN  ...              21494.0
1         NaN  ...              96833.0
2         NaN  ...               5351.0
3         NaN  ...              86887.0
4         NaN  ...              15890.0

[5 rows x 8 columns]

## 2. Conferência dos dados

In [2]:
pop_2010 = "População 2010 (Alterações de Limites até 2022)1"
pop_2022 = "População Censo 2022"

base_censo[pop_2010] = pd.to_numeric(base_censo[pop_2010], errors="coerce")
base_censo[pop_2022] = pd.to_numeric(base_censo[pop_2022], errors="coerce")

base_censo["SALDO_POPULACIONAL"] = base_censo[pop_2022].sub(base_censo[pop_2010])

print("Valores ausentes nas populações:")
print(base_censo[[pop_2010, pop_2022]].isna().sum())

base_censo[["UF", "NOME DO MUNICÍPIO", pop_2010, pop_2022, "SALDO_POPULACIONAL"]].head()

Valores ausentes nas populações:
População 2010 (Alterações de Limites até 2022)1    0
População Censo 2022                                0
dtype: int64

   UF      NOME DO MUNICÍPIO  ...  População Censo 2022  SALDO_POPULACIONAL
0  RO  Alta Floresta D'Oeste  ...               21494.0             -2898.0
1  RO              Ariquemes  ...               96833.0              6480.0
2  RO                 Cabixi  ...                5351.0              -962.0
3  RO                 Cacoal  ...               86887.0              8313.0
4  RO             Cerejeiras  ...               15890.0             -1139.0

[5 rows x 5 columns]

## 3. Análise da variação populacional

In [3]:
qtd_crescimento = (base_censo["SALDO_POPULACIONAL"] > 0).sum()
qtd_reducao = (base_censo["SALDO_POPULACIONAL"] < 0).sum()
qtd_estavel = (base_censo["SALDO_POPULACIONAL"] == 0).sum()

quadro_situacao = pd.DataFrame({
    "Situação": ["Aumento", "Redução", "Sem variação"],
    "Quantidade de municípios": [qtd_crescimento, qtd_reducao, qtd_estavel]
})

quadro_situacao

       Situação  Quantidade de municípios
0       Aumento                      3172
1       Redução                      2395
2  Sem variação                         3

## 4. Consolidação por estado

In [4]:
pop_por_uf = (
    base_censo.groupby("UF", as_index=False)[[pop_2010, pop_2022]]
    .sum()
)

pop_por_uf["SALDO_POPULACIONAL"] = pop_por_uf[pop_2022].sub(pop_por_uf[pop_2010])
pop_por_uf = (
    pop_por_uf.sort_values("SALDO_POPULACIONAL", ascending=False)
    .reset_index(drop=True)
)

pop_por_uf

    UF  ...  SALDO_POPULACIONAL
0   SP  ...           3149039.0
1   SC  ...           1361925.0
2   GO  ...           1054706.0
3   PR  ...            999854.0
4   MG  ...            942659.0
5   MT  ...            623527.0
6   PA  ...            539080.0
7   AM  ...            457628.0
8   CE  ...            343313.0
9   ES  ...            318760.0
10  MS  ...            307989.0
11  PE  ...            262876.0
12  DF  ...            245222.0
13  PB  ...            208159.0
14  MA  ...            201910.0
15  RS  ...            189036.0
16  RR  ...            186228.0
17  PI  ...            152102.0
18  SE  ...            142152.0
19  RN  ...            134702.0
20  TO  ...            128015.0
21  BA  ...            124555.0
22  AC  ...             96459.0
23  RJ  ...             65245.0
24  AP  ...             64233.0
25  RO  ...             18787.0
26  AL  ...              6796.0

[27 rows x 4 columns]

### Principais resultados por estado

In [5]:
print("5 estados com maior aumento líquido:")
display(pop_por_uf.head(5))

print("5 estados com maior redução líquida:")
display(
    pop_por_uf.nsmallest(5, "SALDO_POPULACIONAL")
)

5 estados com maior aumento líquido:

   UF  ...  SALDO_POPULACIONAL
0  SP  ...           3149039.0
1  SC  ...           1361925.0
2  GO  ...           1054706.0
3  PR  ...            999854.0
4  MG  ...            942659.0

[5 rows x 4 columns]

5 estados com maior redução líquida:

    UF  ...  SALDO_POPULACIONAL
26  AL  ...              6796.0
25  RO  ...             18787.0
24  AP  ...             64233.0
23  RJ  ...             65245.0
22  AC  ...             96459.0

[5 rows x 4 columns]

## 5. Detalhamento por município

In [6]:
dados_municipais = base_censo[[
    "UF",
    "COD. UF",
    "COD. MUNIC",
    "NOME DO MUNICÍPIO",
    pop_2010,
    pop_2022,
    "SALDO_POPULACIONAL"
]].copy()

dados_municipais = (
    dados_municipais
    .sort_values("SALDO_POPULACIONAL", ascending=False)
    .reset_index(drop=True)
)

dados_municipais.head(20)

    UF  COD. UF  ...  População Censo 2022 SALDO_POPULACIONAL
0   AM     13.0  ...             2063689.0           261675.0
1   DF     53.0  ...             2817381.0           245222.0
2   SP     35.0  ...            11451999.0           198496.0
3   SP     35.0  ...              723682.0           136866.0
4   GO     52.0  ...             1437366.0           135454.0
5   RR     14.0  ...              413486.0           129173.0
6   SC     42.0  ...              537211.0           115971.0
7   PA     15.0  ...              267836.0           113928.0
8   MS     50.0  ...              898100.0           111326.0
9   PB     25.0  ...              833932.0           110417.0
10  MG     31.0  ...              713224.0           109211.0
11  ES     32.0  ...              520653.0           103323.0
12  SC     42.0  ...              616317.0           101029.0
13  MT     51.0  ...              650877.0            97675.0
14  SP     35.0  ...              698642.0            93960.0
15  PE     26.0  ...              386791.0            92829.0
16  SP     35.0  ...              349935.0            87884.0
17  SC     42.0  ...              222598.0            85264.0
18  MT     51.0  ...              196312.0            83213.0
19  MA     21.0  ...              244579.0            82642.0

[20 rows x 7 columns]

### Maiores aumentos e maiores reduções

In [7]:
print("10 municípios com maior aumento:")
display(dados_municipais.head(10))

print("10 municípios com maior redução:")
display(
    dados_municipais.nsmallest(10, "SALDO_POPULACIONAL")
)

10 municípios com maior aumento:

   UF  COD. UF  ...  População Censo 2022 SALDO_POPULACIONAL
0  AM     13.0  ...             2063689.0           261675.0
1  DF     53.0  ...             2817381.0           245222.0
2  SP     35.0  ...            11451999.0           198496.0
3  SP     35.0  ...              723682.0           136866.0
4  GO     52.0  ...             1437366.0           135454.0
5  RR     14.0  ...              413486.0           129173.0
6  SC     42.0  ...              537211.0           115971.0
7  PA     15.0  ...              267836.0           113928.0
8  MS     50.0  ...              898100.0           111326.0
9  PB     25.0  ...              833932.0           110417.0

[10 rows x 7 columns]

10 municípios com maior redução:

      UF  COD. UF  ...  População Censo 2022 SALDO_POPULACIONAL
5569  BA     29.0  ...             2417678.0          -257978.0
5568  RJ     33.0  ...             6211223.0          -109223.0
5567  RJ     33.0  ...              896744.0          -102984.0
5566  PA     15.0  ...             1303403.0           -89996.0
5565  RS     43.0  ...             1332845.0           -76506.0
5564  MG     31.0  ...             2315560.0           -60049.0
5563  RN     24.0  ...              751300.0           -52439.0
5562  PE     26.0  ...             1488920.0           -48784.0
5561  RJ     33.0  ...              808161.0           -46927.0
5560  CE     23.0  ...             2428708.0           -31004.0

[10 rows x 7 columns]

## 6. Exportação dos resultados

In [8]:
pop_por_uf.to_csv(
    "populacao_por_estado.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

dados_municipais.to_csv(
    "populacao_por_municipio.csv",
    sep=";",
    index=False,
    encoding="utf-8-sig"
)

print("Arquivos de população por estado e por município foram atualizados.")

Arquivos de população por estado e por município foram atualizados.